### ISSUE TITLE
plugin not running on Prismatik 5.11.2.31

### ISSUE THREAD

**Issue by dfpreda** [BKrajancic/Prismatik-Lightbulb-Addon#1]
Hello @BKrajancic!

First of all i would like to thank you for your work, i've been looking for this integration for ages.
I succesfully installed the openrgb sync plugin following your directions 
but i can't seem to get it running. Everytime i try to turn the plugin on it crashes after a split second 
saying it's not running. Can you please help me get it running? 
![Untitled](https://github.com/BKrajancic/Prismatik-Device-Sync/assets/75398886/ce767ba2-57ae-4eb7-934a-8e8856a30868)

Thank you,
Daniel

**Comment by Supernova4422** [comment]
Hi, can you send me any additional information? My first thought is to check if you've set the IP correctly and that you've set up Prismatik to allow incoming connections. 

I've not put those in the readme unfortunately

**Comment by Supernova4422** [comment]
Oh another thing, have you installed python? I think I might not have set it up correctly for other people's machines so you may need to edit the file to point to your python installation

**Comment by Supernova4422** [comment]
Ok I've had a bit more time to look at my code @dfpreda another question, have you installed the python packages needed?
It looks like there isn't a need to configure the IP address so that might not be the issue.

Another way to get more information that would help me is to manually go to the plugin's directory, run the program using python, then post the result here.

**Comment by dfpreda** [comment]
Hello! I have python installed and all the packages from requirements
![image](https://github.com/BKrajancic/Prismatik-Device-Sync/assets/75398886/0a3f87fa-2435-4b93-9c7d-a49671b3a15d)

i ran main.py and i got this error
![image](https://github.com/BKrajancic/Prismatik-Device-Sync/assets/75398886/50188a4e-8de3-487f-8d8b-2b5cb269ef93)

so i installed pip openrgb-python and now i get this
![image](https://github.com/BKrajancic/Prismatik-Device-Sync/assets/75398886/d4a7a186-b30d-4b90-a5f5-75e21767d90d)

did i install the wrong openrgb-python module? Thank you

**Comment by dfpreda** [comment]
I tried debugging it and found the problem. It was because of the openrg-python module. It timed out when connecting to my sdk server because i opened it on my local ip(to use openrgb with home assistant) instead of localhost 127.0.0.1. Now as i changed it to 127.0.0.1 the plugin is working fine, but my home assistant integration no longer finds openrgb sdk server, so i'm gonna have to fix that in the following..years maybe haha

Thank you very much for your help and for your tool

**Comment by Supernova4422** [comment]
No worries, really glad to see someone else making use of the project (funnily enough I've not used it in ages)
